// Generated by CoffeeScript 1.8.0
(function() {
  window.app = angular.module('ngShipper', ['ngMaterial', 'ngRoute']).controller('AppCtrl', [function($scope) {}]);

}).call(this);

//# sourceMappingURL=app.js.map
