// Generated by CoffeeScript 1.8.0
(function() {
  window.app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/home', {
        controller: 'HomeCtrl',
        templateUrl: 'app/home/home.html'
      });
    }
  ]).controller('HomeCtrl', ['$scope', function($scope) {}]);

}).call(this);

//# sourceMappingURL=home.js.map
